name: Deploy to GitHub Pages and Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean gh-pages cache
        run: |
          rm -rf node_modules/.cache
          git rm -rf --cached node_modules/.cache || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g vite
          npm install netlify-cli -g

      - name: Build
        run: |
          chmod +x node_modules/.bin/vite
          npx vite build
        env:
          VITE_BASE_URL: '/'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true

      - name: Deploy to Netlify
        env:
          # Get this from User Settings → Applications → Personal access tokens
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          # Get this from Site Settings → Site information → API ID
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=dist